/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as _fixtures_createMockTournament from "../_fixtures/createMockTournament.js";
import type * as _fixtures_createMockTournamentCompetitor from "../_fixtures/createMockTournamentCompetitor.js";
import type * as _fixtures_fowV4_createMockFowV4MatchResultData from "../_fixtures/fowV4/createMockFowV4MatchResultData.js";
import type * as _model_common_VisibilityLevel from "../_model/common/VisibilityLevel.js";
import type * as _model_common__helpers_buildFilteredQuery from "../_model/common/_helpers/buildFilteredQuery.js";
import type * as _model_common__helpers_checkAuth from "../_model/common/_helpers/checkAuth.js";
import type * as _model_common__helpers_clamp from "../_model/common/_helpers/clamp.js";
import type * as _model_common__helpers_filterWithSearchTerm from "../_model/common/_helpers/filterWithSearchTerm.js";
import type * as _model_common__helpers_gameSystem_computeRankingFactors from "../_model/common/_helpers/gameSystem/computeRankingFactors.js";
import type * as _model_common__helpers_gameSystem_createSortByRanking from "../_model/common/_helpers/gameSystem/createSortByRanking.js";
import type * as _model_common__helpers_gameSystem_divideBaseStats from "../_model/common/_helpers/gameSystem/divideBaseStats.js";
import type * as _model_common__helpers_gameSystem_sumBaseStats from "../_model/common/_helpers/gameSystem/sumBaseStats.js";
import type * as _model_common__helpers_getCountryName from "../_model/common/_helpers/getCountryName.js";
import type * as _model_common__helpers_getEnvironment from "../_model/common/_helpers/getEnvironment.js";
import type * as _model_common__helpers_getRange from "../_model/common/_helpers/getRange.js";
import type * as _model_common__helpers_getStaticEnumConvexValidator from "../_model/common/_helpers/getStaticEnumConvexValidator.js";
import type * as _model_common__helpers_getStorageUrl from "../_model/common/_helpers/getStorageUrl.js";
import type * as _model_common__helpers_intersectArrays from "../_model/common/_helpers/intersectArrays.js";
import type * as _model_common__helpers_notNullOrUndefined from "../_model/common/_helpers/notNullOrUndefined.js";
import type * as _model_common_alignment from "../_model/common/alignment.js";
import type * as _model_common_baseStats from "../_model/common/baseStats.js";
import type * as _model_common_errors from "../_model/common/errors.js";
import type * as _model_common_faction from "../_model/common/faction.js";
import type * as _model_common_gameSystemConfig from "../_model/common/gameSystemConfig.js";
import type * as _model_common_leagueStatus from "../_model/common/leagueStatus.js";
import type * as _model_common_location from "../_model/common/location.js";
import type * as _model_common_matchResultDetails from "../_model/common/matchResultDetails.js";
import type * as _model_common_rankingFactor from "../_model/common/rankingFactor.js";
import type * as _model_common_scoreAdjustment from "../_model/common/scoreAdjustment.js";
import type * as _model_common_themes from "../_model/common/themes.js";
import type * as _model_common_tournamentPairingConfig from "../_model/common/tournamentPairingConfig.js";
import type * as _model_common_tournamentStatus from "../_model/common/tournamentStatus.js";
import type * as _model_common_types from "../_model/common/types.js";
import type * as _model_files_index from "../_model/files/index.js";
import type * as _model_files_queries_getFileMetadata from "../_model/files/queries/getFileMetadata.js";
import type * as _model_files_queries_getFileUrl from "../_model/files/queries/getFileUrl.js";
import type * as _model_friendships__helpers_deepenFriendship from "../_model/friendships/_helpers/deepenFriendship.js";
import type * as _model_friendships_index from "../_model/friendships/index.js";
import type * as _model_friendships_mutations_confirmFriendship from "../_model/friendships/mutations/confirmFriendship.js";
import type * as _model_friendships_mutations_createFriendship from "../_model/friendships/mutations/createFriendship.js";
import type * as _model_friendships_mutations_deleteFriendship from "../_model/friendships/mutations/deleteFriendship.js";
import type * as _model_friendships_queries_getFriendship from "../_model/friendships/queries/getFriendship.js";
import type * as _model_friendships_queries_getFriendshipsByUser from "../_model/friendships/queries/getFriendshipsByUser.js";
import type * as _model_friendships_table from "../_model/friendships/table.js";
import type * as _model_gameSystems_battlefront_flamesOfWarV4__helpers_deepenListData from "../_model/gameSystems/battlefront/flamesOfWarV4/_helpers/deepenListData.js";
import type * as _model_gameSystems_battlefront_flamesOfWarV4__model_listData from "../_model/gameSystems/battlefront/flamesOfWarV4/_model/listData.js";
import type * as _model_gameSystems_battlefront_flamesOfWarV4_index from "../_model/gameSystems/battlefront/flamesOfWarV4/index.js";
import type * as _model_gameSystems_index from "../_model/gameSystems/index.js";
import type * as _model_leagueOrganizers__helpers_checkUserIsLeagueOrganizer from "../_model/leagueOrganizers/_helpers/checkUserIsLeagueOrganizer.js";
import type * as _model_leagueOrganizers__helpers_deepenLeagueOrganizer from "../_model/leagueOrganizers/_helpers/deepenLeagueOrganizer.js";
import type * as _model_leagueOrganizers_index from "../_model/leagueOrganizers/index.js";
import type * as _model_leagueOrganizers_mutations_createLeagueOrganizer from "../_model/leagueOrganizers/mutations/createLeagueOrganizer.js";
import type * as _model_leagueOrganizers_mutations_deleteLeagueOrganizer from "../_model/leagueOrganizers/mutations/deleteLeagueOrganizer.js";
import type * as _model_leagueOrganizers_queries_getLeagueOrganizersByLeague from "../_model/leagueOrganizers/queries/getLeagueOrganizersByLeague.js";
import type * as _model_leagueOrganizers_table from "../_model/leagueOrganizers/table.js";
import type * as _model_leagueOrganizers_types from "../_model/leagueOrganizers/types.js";
import type * as _model_leagueRankings__helpers_deepenLeagueRanking from "../_model/leagueRankings/_helpers/deepenLeagueRanking.js";
import type * as _model_leagueRankings_index from "../_model/leagueRankings/index.js";
import type * as _model_leagueRankings_mutations_refreshLeagueRanking from "../_model/leagueRankings/mutations/refreshLeagueRanking.js";
import type * as _model_leagueRankings_queries_getLeagueRankingFullResults from "../_model/leagueRankings/queries/getLeagueRankingFullResults.js";
import type * as _model_leagueRankings_queries_getLeagueRankingsByLeague from "../_model/leagueRankings/queries/getLeagueRankingsByLeague.js";
import type * as _model_leagueRankings_table from "../_model/leagueRankings/table.js";
import type * as _model_leagueRankings_types from "../_model/leagueRankings/types.js";
import type * as _model_leagues__helpers_calculateRankings from "../_model/leagues/_helpers/calculateRankings.js";
import type * as _model_leagues__helpers_checkLeagueVisibility from "../_model/leagues/_helpers/checkLeagueVisibility.js";
import type * as _model_leagues__helpers_deepenLeague from "../_model/leagues/_helpers/deepenLeague.js";
import type * as _model_leagues_index from "../_model/leagues/index.js";
import type * as _model_leagues_mutations_createLeague from "../_model/leagues/mutations/createLeague.js";
import type * as _model_leagues_mutations_refreshLeagueRankings from "../_model/leagues/mutations/refreshLeagueRankings.js";
import type * as _model_leagues_queries_getLeague from "../_model/leagues/queries/getLeague.js";
import type * as _model_leagues_queries_getLeagues from "../_model/leagues/queries/getLeagues.js";
import type * as _model_leagues_table from "../_model/leagues/table.js";
import type * as _model_leagues_types from "../_model/leagues/types.js";
import type * as _model_lists__helpers_deepenList from "../_model/lists/_helpers/deepenList.js";
import type * as _model_lists_actions_extractListData from "../_model/lists/actions/extractListData.js";
import type * as _model_lists_actions_importList from "../_model/lists/actions/importList.js";
import type * as _model_lists_index from "../_model/lists/index.js";
import type * as _model_lists_mutations_createList from "../_model/lists/mutations/createList.js";
import type * as _model_lists_queries_getList from "../_model/lists/queries/getList.js";
import type * as _model_lists_table from "../_model/lists/table.js";
import type * as _model_matchResultComments__helpers_deepenMatchResultComment from "../_model/matchResultComments/_helpers/deepenMatchResultComment.js";
import type * as _model_matchResultComments_index from "../_model/matchResultComments/index.js";
import type * as _model_matchResultComments_mutations_addMatchResultComment from "../_model/matchResultComments/mutations/addMatchResultComment.js";
import type * as _model_matchResultComments_queries_getMatchResultComment from "../_model/matchResultComments/queries/getMatchResultComment.js";
import type * as _model_matchResultComments_queries_getMatchResultCommentsByMatchResult from "../_model/matchResultComments/queries/getMatchResultCommentsByMatchResult.js";
import type * as _model_matchResultComments_queries_getMatchResultCommentsByUser from "../_model/matchResultComments/queries/getMatchResultCommentsByUser.js";
import type * as _model_matchResultComments_table from "../_model/matchResultComments/table.js";
import type * as _model_matchResultLikes__helpers_deepenMatchResultLike from "../_model/matchResultLikes/_helpers/deepenMatchResultLike.js";
import type * as _model_matchResultLikes_index from "../_model/matchResultLikes/index.js";
import type * as _model_matchResultLikes_mutations_toggleMatchResultLike from "../_model/matchResultLikes/mutations/toggleMatchResultLike.js";
import type * as _model_matchResultLikes_queries_getMatchResultLike from "../_model/matchResultLikes/queries/getMatchResultLike.js";
import type * as _model_matchResultLikes_queries_getMatchResultLikesByMatchResult from "../_model/matchResultLikes/queries/getMatchResultLikesByMatchResult.js";
import type * as _model_matchResultLikes_queries_getMatchResultLikesByUser from "../_model/matchResultLikes/queries/getMatchResultLikesByUser.js";
import type * as _model_matchResultLikes_table from "../_model/matchResultLikes/table.js";
import type * as _model_matchResults__helpers_checkMatchResultAuth from "../_model/matchResults/_helpers/checkMatchResultAuth.js";
import type * as _model_matchResults__helpers_checkMatchResultDetailsVisibility from "../_model/matchResults/_helpers/checkMatchResultDetailsVisibility.js";
import type * as _model_matchResults__helpers_deepenMatchResult from "../_model/matchResults/_helpers/deepenMatchResult.js";
import type * as _model_matchResults__helpers_deepenMatchResultDetails from "../_model/matchResults/_helpers/deepenMatchResultDetails.js";
import type * as _model_matchResults__helpers_getShallowMatchResult from "../_model/matchResults/_helpers/getShallowMatchResult.js";
import type * as _model_matchResults_index from "../_model/matchResults/index.js";
import type * as _model_matchResults_mutations_addPhotoToMatchResult from "../_model/matchResults/mutations/addPhotoToMatchResult.js";
import type * as _model_matchResults_mutations_createMatchResult from "../_model/matchResults/mutations/createMatchResult.js";
import type * as _model_matchResults_mutations_deleteMatchResult from "../_model/matchResults/mutations/deleteMatchResult.js";
import type * as _model_matchResults_mutations_deleteMatchResultsByTournamentRound from "../_model/matchResults/mutations/deleteMatchResultsByTournamentRound.js";
import type * as _model_matchResults_mutations_updateMatchResult from "../_model/matchResults/mutations/updateMatchResult.js";
import type * as _model_matchResults_queries_getMatchResult from "../_model/matchResults/queries/getMatchResult.js";
import type * as _model_matchResults_queries_getMatchResults from "../_model/matchResults/queries/getMatchResults.js";
import type * as _model_matchResults_queries_getMatchResultsByTournament from "../_model/matchResults/queries/getMatchResultsByTournament.js";
import type * as _model_matchResults_queries_getMatchResultsByTournamentPairing from "../_model/matchResults/queries/getMatchResultsByTournamentPairing.js";
import type * as _model_matchResults_queries_getMatchResultsByTournamentRound from "../_model/matchResults/queries/getMatchResultsByTournamentRound.js";
import type * as _model_matchResults_queries_getMatchResultsByUser from "../_model/matchResults/queries/getMatchResultsByUser.js";
import type * as _model_matchResults_table from "../_model/matchResults/table.js";
import type * as _model_matchResults_triggers from "../_model/matchResults/triggers.js";
import type * as _model_photos_index from "../_model/photos/index.js";
import type * as _model_photos_mutations_createPhoto from "../_model/photos/mutations/createPhoto.js";
import type * as _model_photos_queries_getPhoto from "../_model/photos/queries/getPhoto.js";
import type * as _model_photos_table from "../_model/photos/table.js";
import type * as _model_tournamentCompetitors__helpers_deepenTournamentCompetitor from "../_model/tournamentCompetitors/_helpers/deepenTournamentCompetitor.js";
import type * as _model_tournamentCompetitors__helpers_getAvailableActions from "../_model/tournamentCompetitors/_helpers/getAvailableActions.js";
import type * as _model_tournamentCompetitors__helpers_getDetails from "../_model/tournamentCompetitors/_helpers/getDetails.js";
import type * as _model_tournamentCompetitors__helpers_getDisplayName from "../_model/tournamentCompetitors/_helpers/getDisplayName.js";
import type * as _model_tournamentCompetitors__helpers_sortTournamentCompetitorsByName from "../_model/tournamentCompetitors/_helpers/sortTournamentCompetitorsByName.js";
import type * as _model_tournamentCompetitors_index from "../_model/tournamentCompetitors/index.js";
import type * as _model_tournamentCompetitors_mutations_createTournamentCompetitor from "../_model/tournamentCompetitors/mutations/createTournamentCompetitor.js";
import type * as _model_tournamentCompetitors_mutations_deleteTournamentCompetitor from "../_model/tournamentCompetitors/mutations/deleteTournamentCompetitor.js";
import type * as _model_tournamentCompetitors_mutations_toggleTournamentCompetitorActive from "../_model/tournamentCompetitors/mutations/toggleTournamentCompetitorActive.js";
import type * as _model_tournamentCompetitors_mutations_updateTournamentCompetitor from "../_model/tournamentCompetitors/mutations/updateTournamentCompetitor.js";
import type * as _model_tournamentCompetitors_queries_getAvailableTournamentCompetitorActions from "../_model/tournamentCompetitors/queries/getAvailableTournamentCompetitorActions.js";
import type * as _model_tournamentCompetitors_queries_getTournamentCompetitor from "../_model/tournamentCompetitors/queries/getTournamentCompetitor.js";
import type * as _model_tournamentCompetitors_queries_getTournamentCompetitors from "../_model/tournamentCompetitors/queries/getTournamentCompetitors.js";
import type * as _model_tournamentCompetitors_queries_getTournamentCompetitorsByTournament from "../_model/tournamentCompetitors/queries/getTournamentCompetitorsByTournament.js";
import type * as _model_tournamentCompetitors_table from "../_model/tournamentCompetitors/table.js";
import type * as _model_tournamentCompetitors_triggers from "../_model/tournamentCompetitors/triggers.js";
import type * as _model_tournamentOrganizers__helpers_checkUserIsTournamentOrganizer from "../_model/tournamentOrganizers/_helpers/checkUserIsTournamentOrganizer.js";
import type * as _model_tournamentOrganizers__helpers_deepenTournamentOrganizer from "../_model/tournamentOrganizers/_helpers/deepenTournamentOrganizer.js";
import type * as _model_tournamentOrganizers_index from "../_model/tournamentOrganizers/index.js";
import type * as _model_tournamentOrganizers_mutations_createTournamentOrganizer from "../_model/tournamentOrganizers/mutations/createTournamentOrganizer.js";
import type * as _model_tournamentOrganizers_mutations_deleteTournamentOrganizer from "../_model/tournamentOrganizers/mutations/deleteTournamentOrganizer.js";
import type * as _model_tournamentOrganizers_queries_getTournamentOrganizersByTournament from "../_model/tournamentOrganizers/queries/getTournamentOrganizersByTournament.js";
import type * as _model_tournamentOrganizers_queries_getTournamentOrganizersByUser from "../_model/tournamentOrganizers/queries/getTournamentOrganizersByUser.js";
import type * as _model_tournamentOrganizers_table from "../_model/tournamentOrganizers/table.js";
import type * as _model_tournamentOrganizers_types from "../_model/tournamentOrganizers/types.js";
import type * as _model_tournamentPairings__helpers_assignBye from "../_model/tournamentPairings/_helpers/assignBye.js";
import type * as _model_tournamentPairings__helpers_assignTables from "../_model/tournamentPairings/_helpers/assignTables.js";
import type * as _model_tournamentPairings__helpers_checkIfPairingIsRepeat from "../_model/tournamentPairings/_helpers/checkIfPairingIsRepeat.js";
import type * as _model_tournamentPairings__helpers_checkIfPairingIsSameAlignment from "../_model/tournamentPairings/_helpers/checkIfPairingIsSameAlignment.js";
import type * as _model_tournamentPairings__helpers_deepenTournamentPairing from "../_model/tournamentPairings/_helpers/deepenTournamentPairing.js";
import type * as _model_tournamentPairings__helpers_generateDraftPairings from "../_model/tournamentPairings/_helpers/generateDraftPairings.js";
import type * as _model_tournamentPairings__helpers_getTournamentPairingDeep from "../_model/tournamentPairings/_helpers/getTournamentPairingDeep.js";
import type * as _model_tournamentPairings__helpers_getTournamentPairingShallow from "../_model/tournamentPairings/_helpers/getTournamentPairingShallow.js";
import type * as _model_tournamentPairings__helpers_getTournamentPairingUserIds from "../_model/tournamentPairings/_helpers/getTournamentPairingUserIds.js";
import type * as _model_tournamentPairings__helpers_shuffle from "../_model/tournamentPairings/_helpers/shuffle.js";
import type * as _model_tournamentPairings__helpers_sortByRank from "../_model/tournamentPairings/_helpers/sortByRank.js";
import type * as _model_tournamentPairings__helpers_sortCompetitorPairs from "../_model/tournamentPairings/_helpers/sortCompetitorPairs.js";
import type * as _model_tournamentPairings__helpers_sortPairingsByTable from "../_model/tournamentPairings/_helpers/sortPairingsByTable.js";
import type * as _model_tournamentPairings__helpers_validateTournamentPairing from "../_model/tournamentPairings/_helpers/validateTournamentPairing.js";
import type * as _model_tournamentPairings_actions_generateDraftTournamentPairings from "../_model/tournamentPairings/actions/generateDraftTournamentPairings.js";
import type * as _model_tournamentPairings_actions_generateTableAssignments from "../_model/tournamentPairings/actions/generateTableAssignments.js";
import type * as _model_tournamentPairings_index from "../_model/tournamentPairings/index.js";
import type * as _model_tournamentPairings_mutations_createTournamentPairings from "../_model/tournamentPairings/mutations/createTournamentPairings.js";
import type * as _model_tournamentPairings_mutations_deleteTournamentPairings from "../_model/tournamentPairings/mutations/deleteTournamentPairings.js";
import type * as _model_tournamentPairings_queries_getActiveTournamentPairingsByUser from "../_model/tournamentPairings/queries/getActiveTournamentPairingsByUser.js";
import type * as _model_tournamentPairings_queries_getDraftTournamentPairings from "../_model/tournamentPairings/queries/getDraftTournamentPairings.js";
import type * as _model_tournamentPairings_queries_getTournamentPairing from "../_model/tournamentPairings/queries/getTournamentPairing.js";
import type * as _model_tournamentPairings_queries_getTournamentPairings from "../_model/tournamentPairings/queries/getTournamentPairings.js";
import type * as _model_tournamentPairings_queries_getTournamentPairingsByTournament from "../_model/tournamentPairings/queries/getTournamentPairingsByTournament.js";
import type * as _model_tournamentPairings_table from "../_model/tournamentPairings/table.js";
import type * as _model_tournamentPairings_types from "../_model/tournamentPairings/types.js";
import type * as _model_tournamentRegistrations__helpers_checkUserIsRegistered from "../_model/tournamentRegistrations/_helpers/checkUserIsRegistered.js";
import type * as _model_tournamentRegistrations__helpers_deepenTournamentRegistration from "../_model/tournamentRegistrations/_helpers/deepenTournamentRegistration.js";
import type * as _model_tournamentRegistrations__helpers_getAvailableActions from "../_model/tournamentRegistrations/_helpers/getAvailableActions.js";
import type * as _model_tournamentRegistrations__helpers_getCreateSuccessMessage from "../_model/tournamentRegistrations/_helpers/getCreateSuccessMessage.js";
import type * as _model_tournamentRegistrations__helpers_getDeleteSuccessMessage from "../_model/tournamentRegistrations/_helpers/getDeleteSuccessMessage.js";
import type * as _model_tournamentRegistrations_index from "../_model/tournamentRegistrations/index.js";
import type * as _model_tournamentRegistrations_mutations_createTournamentRegistration from "../_model/tournamentRegistrations/mutations/createTournamentRegistration.js";
import type * as _model_tournamentRegistrations_mutations_deleteTournamentRegistration from "../_model/tournamentRegistrations/mutations/deleteTournamentRegistration.js";
import type * as _model_tournamentRegistrations_mutations_toggleTournamentRegistrationActive from "../_model/tournamentRegistrations/mutations/toggleTournamentRegistrationActive.js";
import type * as _model_tournamentRegistrations_mutations_updateTournamentRegistration from "../_model/tournamentRegistrations/mutations/updateTournamentRegistration.js";
import type * as _model_tournamentRegistrations_queries_getTournamentRegistrationByTournamentUser from "../_model/tournamentRegistrations/queries/getTournamentRegistrationByTournamentUser.js";
import type * as _model_tournamentRegistrations_queries_getTournamentRegistrationsByCompetitor from "../_model/tournamentRegistrations/queries/getTournamentRegistrationsByCompetitor.js";
import type * as _model_tournamentRegistrations_queries_getTournamentRegistrationsByTournament from "../_model/tournamentRegistrations/queries/getTournamentRegistrationsByTournament.js";
import type * as _model_tournamentRegistrations_queries_getTournamentRegistrationsByUser from "../_model/tournamentRegistrations/queries/getTournamentRegistrationsByUser.js";
import type * as _model_tournamentRegistrations_table from "../_model/tournamentRegistrations/table.js";
import type * as _model_tournamentRegistrations_types from "../_model/tournamentRegistrations/types.js";
import type * as _model_tournamentResults__helpers_aggregateTournamentData from "../_model/tournamentResults/_helpers/aggregateTournamentData.js";
import type * as _model_tournamentResults__helpers_applyScoreAdjustments from "../_model/tournamentResults/_helpers/applyScoreAdjustments.js";
import type * as _model_tournamentResults_index from "../_model/tournamentResults/index.js";
import type * as _model_tournamentResults_mutations_refreshTournamentResult from "../_model/tournamentResults/mutations/refreshTournamentResult.js";
import type * as _model_tournamentResults_queries_getTournamentResultsByCompetitor from "../_model/tournamentResults/queries/getTournamentResultsByCompetitor.js";
import type * as _model_tournamentResults_queries_getTournamentResultsByGameSystem from "../_model/tournamentResults/queries/getTournamentResultsByGameSystem.js";
import type * as _model_tournamentResults_queries_getTournamentResultsByRound from "../_model/tournamentResults/queries/getTournamentResultsByRound.js";
import type * as _model_tournamentResults_queries_getTournamentResultsByUser from "../_model/tournamentResults/queries/getTournamentResultsByUser.js";
import type * as _model_tournamentResults_table from "../_model/tournamentResults/table.js";
import type * as _model_tournamentResults_triggers from "../_model/tournamentResults/triggers.js";
import type * as _model_tournamentResults_types from "../_model/tournamentResults/types.js";
import type * as _model_tournamentTimers__helpers_convertRoundStructureToMs from "../_model/tournamentTimers/_helpers/convertRoundStructureToMs.js";
import type * as _model_tournamentTimers__helpers_deepenTournamentTimer from "../_model/tournamentTimers/_helpers/deepenTournamentTimer.js";
import type * as _model_tournamentTimers__helpers_getTournamentTimerShallow from "../_model/tournamentTimers/_helpers/getTournamentTimerShallow.js";
import type * as _model_tournamentTimers_index from "../_model/tournamentTimers/index.js";
import type * as _model_tournamentTimers_mutations_createTournamentTimer from "../_model/tournamentTimers/mutations/createTournamentTimer.js";
import type * as _model_tournamentTimers_mutations_deleteTournamentTimerByTournament from "../_model/tournamentTimers/mutations/deleteTournamentTimerByTournament.js";
import type * as _model_tournamentTimers_mutations_resetTournamentTimer from "../_model/tournamentTimers/mutations/resetTournamentTimer.js";
import type * as _model_tournamentTimers_mutations_setTournamentTimerPhase from "../_model/tournamentTimers/mutations/setTournamentTimerPhase.js";
import type * as _model_tournamentTimers_mutations_toggleTournamentTimer from "../_model/tournamentTimers/mutations/toggleTournamentTimer.js";
import type * as _model_tournamentTimers_queries_getTournamentTimer from "../_model/tournamentTimers/queries/getTournamentTimer.js";
import type * as _model_tournamentTimers_queries_getTournamentTimerByTournament from "../_model/tournamentTimers/queries/getTournamentTimerByTournament.js";
import type * as _model_tournamentTimers_table from "../_model/tournamentTimers/table.js";
import type * as _model_tournaments__helpers_checkTournamentAuth from "../_model/tournaments/_helpers/checkTournamentAuth.js";
import type * as _model_tournaments__helpers_checkTournamentVisibility from "../_model/tournaments/_helpers/checkTournamentVisibility.js";
import type * as _model_tournaments__helpers_deepenTournament from "../_model/tournaments/_helpers/deepenTournament.js";
import type * as _model_tournaments__helpers_extractSearchTokens from "../_model/tournaments/_helpers/extractSearchTokens.js";
import type * as _model_tournaments__helpers_getAvailableActions from "../_model/tournaments/_helpers/getAvailableActions.js";
import type * as _model_tournaments__helpers_getDisplayName from "../_model/tournaments/_helpers/getDisplayName.js";
import type * as _model_tournaments__helpers_getTournamentDeep from "../_model/tournaments/_helpers/getTournamentDeep.js";
import type * as _model_tournaments__helpers_getTournamentNextRound from "../_model/tournaments/_helpers/getTournamentNextRound.js";
import type * as _model_tournaments__helpers_getTournamentPlayerUserIds from "../_model/tournaments/_helpers/getTournamentPlayerUserIds.js";
import type * as _model_tournaments__helpers_getTournamentShallow from "../_model/tournaments/_helpers/getTournamentShallow.js";
import type * as _model_tournaments_actions_exportFowV4TournamentMatchData from "../_model/tournaments/actions/exportFowV4TournamentMatchData.js";
import type * as _model_tournaments_index from "../_model/tournaments/index.js";
import type * as _model_tournaments_mutations_createTournament from "../_model/tournaments/mutations/createTournament.js";
import type * as _model_tournaments_mutations_deleteTournament from "../_model/tournaments/mutations/deleteTournament.js";
import type * as _model_tournaments_mutations_endTournament from "../_model/tournaments/mutations/endTournament.js";
import type * as _model_tournaments_mutations_endTournamentRound from "../_model/tournaments/mutations/endTournamentRound.js";
import type * as _model_tournaments_mutations_publishTournament from "../_model/tournaments/mutations/publishTournament.js";
import type * as _model_tournaments_mutations_startTournament from "../_model/tournaments/mutations/startTournament.js";
import type * as _model_tournaments_mutations_startTournamentRound from "../_model/tournaments/mutations/startTournamentRound.js";
import type * as _model_tournaments_mutations_toggleTournamentAlignmentsRevealed from "../_model/tournaments/mutations/toggleTournamentAlignmentsRevealed.js";
import type * as _model_tournaments_mutations_updateTournament from "../_model/tournaments/mutations/updateTournament.js";
import type * as _model_tournaments_queries_getTournament from "../_model/tournaments/queries/getTournament.js";
import type * as _model_tournaments_queries_getTournamentByTournamentPairing from "../_model/tournaments/queries/getTournamentByTournamentPairing.js";
import type * as _model_tournaments_queries_getTournamentOpenRound from "../_model/tournaments/queries/getTournamentOpenRound.js";
import type * as _model_tournaments_queries_getTournaments from "../_model/tournaments/queries/getTournaments.js";
import type * as _model_tournaments_table from "../_model/tournaments/table.js";
import type * as _model_userPreferences_index from "../_model/userPreferences/index.js";
import type * as _model_userPreferences_mutations from "../_model/userPreferences/mutations.js";
import type * as _model_userPreferences_queries from "../_model/userPreferences/queries.js";
import type * as _model_userPreferences_table from "../_model/userPreferences/table.js";
import type * as _model_users__helpers_checkUserAuth from "../_model/users/_helpers/checkUserAuth.js";
import type * as _model_users__helpers_checkUserRelationshipLevel from "../_model/users/_helpers/checkUserRelationshipLevel.js";
import type * as _model_users__helpers_checkUserTournamentRelationship from "../_model/users/_helpers/checkUserTournamentRelationship.js";
import type * as _model_users__helpers_createClaimToken from "../_model/users/_helpers/createClaimToken.js";
import type * as _model_users__helpers_extractSearchTokens from "../_model/users/_helpers/extractSearchTokens.js";
import type * as _model_users__helpers_formatUserRealName from "../_model/users/_helpers/formatUserRealName.js";
import type * as _model_users__helpers_generateUsername from "../_model/users/_helpers/generateUsername.js";
import type * as _model_users__helpers_getShallowUser from "../_model/users/_helpers/getShallowUser.js";
import type * as _model_users__helpers_hashClaimToken from "../_model/users/_helpers/hashClaimToken.js";
import type * as _model_users__helpers_redactUser from "../_model/users/_helpers/redactUser.js";
import type * as _model_users_actions_claimUser from "../_model/users/actions/claimUser.js";
import type * as _model_users_actions_internal_addContactToResend from "../_model/users/actions/internal/addContactToResend.js";
import type * as _model_users_actions_internal_setUserDefaultAvatar from "../_model/users/actions/internal/setUserDefaultAvatar.js";
import type * as _model_users_actions_inviteUser from "../_model/users/actions/inviteUser.js";
import type * as _model_users_index from "../_model/users/index.js";
import type * as _model_users_mutations_internal_deleteUserClaimToken from "../_model/users/mutations/internal/deleteUserClaimToken.js";
import type * as _model_users_mutations_internal_updateUserClaimToken from "../_model/users/mutations/internal/updateUserClaimToken.js";
import type * as _model_users_mutations_updateUser from "../_model/users/mutations/updateUser.js";
import type * as _model_users_mutations_updateUserAvatar from "../_model/users/mutations/updateUserAvatar.js";
import type * as _model_users_mutations_updateUserAvatarNoAuth from "../_model/users/mutations/updateUserAvatarNoAuth.js";
import type * as _model_users_queries_getCurrentUser from "../_model/users/queries/getCurrentUser.js";
import type * as _model_users_queries_getUser from "../_model/users/queries/getUser.js";
import type * as _model_users_queries_getUsers from "../_model/users/queries/getUsers.js";
import type * as _model_users_queries_internal_getUserByClaimToken from "../_model/users/queries/internal/getUserByClaimToken.js";
import type * as _model_users_queries_internal_getUserByEmail from "../_model/users/queries/internal/getUserByEmail.js";
import type * as _model_users_table from "../_model/users/table.js";
import type * as _model_utils__helpers_testUsers from "../_model/utils/_helpers/testUsers.js";
import type * as _model_utils_actions_populateUsers from "../_model/utils/actions/populateUsers.js";
import type * as _model_utils_createTestTournament from "../_model/utils/createTestTournament.js";
import type * as _model_utils_createTestTournamentMatchResults from "../_model/utils/createTestTournamentMatchResults.js";
import type * as _model_utils_createTestUsers from "../_model/utils/createTestUsers.js";
import type * as _model_utils_deleteTestTournament from "../_model/utils/deleteTestTournament.js";
import type * as _model_utils_index from "../_model/utils/index.js";
import type * as _model_utils_mergeUser from "../_model/utils/mergeUser.js";
import type * as _model_utils_mutations_refreshSearchIndex from "../_model/utils/mutations/refreshSearchIndex.js";
import type * as _model_utils_mutations_revealTournamentPlayerNames from "../_model/utils/mutations/revealTournamentPlayerNames.js";
import type * as auth from "../auth.js";
import type * as crons from "../crons.js";
import type * as emails_InviteUserEmail from "../emails/InviteUserEmail.js";
import type * as emails_PasswordResetEmail from "../emails/PasswordResetEmail.js";
import type * as emails_Wrapper from "../emails/Wrapper.js";
import type * as emails_styles from "../emails/styles.js";
import type * as files from "../files.js";
import type * as friendships from "../friendships.js";
import type * as functions from "../functions.js";
import type * as generateFileUploadUrl from "../generateFileUploadUrl.js";
import type * as http from "../http.js";
import type * as leagueRankings from "../leagueRankings.js";
import type * as leagues from "../leagues.js";
import type * as lists from "../lists.js";
import type * as matchResultComments from "../matchResultComments.js";
import type * as matchResultLikes from "../matchResultLikes.js";
import type * as matchResults from "../matchResults.js";
import type * as migrations from "../migrations.js";
import type * as photos from "../photos.js";
import type * as scheduledTasks from "../scheduledTasks.js";
import type * as tournamentCompetitors from "../tournamentCompetitors.js";
import type * as tournamentPairings from "../tournamentPairings.js";
import type * as tournamentRegistrations from "../tournamentRegistrations.js";
import type * as tournamentResults from "../tournamentResults.js";
import type * as tournamentTimers from "../tournamentTimers.js";
import type * as tournaments from "../tournaments.js";
import type * as userPreferences from "../userPreferences.js";
import type * as users from "../users.js";
import type * as utils from "../utils.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "_fixtures/createMockTournament": typeof _fixtures_createMockTournament;
  "_fixtures/createMockTournamentCompetitor": typeof _fixtures_createMockTournamentCompetitor;
  "_fixtures/fowV4/createMockFowV4MatchResultData": typeof _fixtures_fowV4_createMockFowV4MatchResultData;
  "_model/common/VisibilityLevel": typeof _model_common_VisibilityLevel;
  "_model/common/_helpers/buildFilteredQuery": typeof _model_common__helpers_buildFilteredQuery;
  "_model/common/_helpers/checkAuth": typeof _model_common__helpers_checkAuth;
  "_model/common/_helpers/clamp": typeof _model_common__helpers_clamp;
  "_model/common/_helpers/filterWithSearchTerm": typeof _model_common__helpers_filterWithSearchTerm;
  "_model/common/_helpers/gameSystem/computeRankingFactors": typeof _model_common__helpers_gameSystem_computeRankingFactors;
  "_model/common/_helpers/gameSystem/createSortByRanking": typeof _model_common__helpers_gameSystem_createSortByRanking;
  "_model/common/_helpers/gameSystem/divideBaseStats": typeof _model_common__helpers_gameSystem_divideBaseStats;
  "_model/common/_helpers/gameSystem/sumBaseStats": typeof _model_common__helpers_gameSystem_sumBaseStats;
  "_model/common/_helpers/getCountryName": typeof _model_common__helpers_getCountryName;
  "_model/common/_helpers/getEnvironment": typeof _model_common__helpers_getEnvironment;
  "_model/common/_helpers/getRange": typeof _model_common__helpers_getRange;
  "_model/common/_helpers/getStaticEnumConvexValidator": typeof _model_common__helpers_getStaticEnumConvexValidator;
  "_model/common/_helpers/getStorageUrl": typeof _model_common__helpers_getStorageUrl;
  "_model/common/_helpers/intersectArrays": typeof _model_common__helpers_intersectArrays;
  "_model/common/_helpers/notNullOrUndefined": typeof _model_common__helpers_notNullOrUndefined;
  "_model/common/alignment": typeof _model_common_alignment;
  "_model/common/baseStats": typeof _model_common_baseStats;
  "_model/common/errors": typeof _model_common_errors;
  "_model/common/faction": typeof _model_common_faction;
  "_model/common/gameSystemConfig": typeof _model_common_gameSystemConfig;
  "_model/common/leagueStatus": typeof _model_common_leagueStatus;
  "_model/common/location": typeof _model_common_location;
  "_model/common/matchResultDetails": typeof _model_common_matchResultDetails;
  "_model/common/rankingFactor": typeof _model_common_rankingFactor;
  "_model/common/scoreAdjustment": typeof _model_common_scoreAdjustment;
  "_model/common/themes": typeof _model_common_themes;
  "_model/common/tournamentPairingConfig": typeof _model_common_tournamentPairingConfig;
  "_model/common/tournamentStatus": typeof _model_common_tournamentStatus;
  "_model/common/types": typeof _model_common_types;
  "_model/files/index": typeof _model_files_index;
  "_model/files/queries/getFileMetadata": typeof _model_files_queries_getFileMetadata;
  "_model/files/queries/getFileUrl": typeof _model_files_queries_getFileUrl;
  "_model/friendships/_helpers/deepenFriendship": typeof _model_friendships__helpers_deepenFriendship;
  "_model/friendships/index": typeof _model_friendships_index;
  "_model/friendships/mutations/confirmFriendship": typeof _model_friendships_mutations_confirmFriendship;
  "_model/friendships/mutations/createFriendship": typeof _model_friendships_mutations_createFriendship;
  "_model/friendships/mutations/deleteFriendship": typeof _model_friendships_mutations_deleteFriendship;
  "_model/friendships/queries/getFriendship": typeof _model_friendships_queries_getFriendship;
  "_model/friendships/queries/getFriendshipsByUser": typeof _model_friendships_queries_getFriendshipsByUser;
  "_model/friendships/table": typeof _model_friendships_table;
  "_model/gameSystems/battlefront/flamesOfWarV4/_helpers/deepenListData": typeof _model_gameSystems_battlefront_flamesOfWarV4__helpers_deepenListData;
  "_model/gameSystems/battlefront/flamesOfWarV4/_model/listData": typeof _model_gameSystems_battlefront_flamesOfWarV4__model_listData;
  "_model/gameSystems/battlefront/flamesOfWarV4/index": typeof _model_gameSystems_battlefront_flamesOfWarV4_index;
  "_model/gameSystems/index": typeof _model_gameSystems_index;
  "_model/leagueOrganizers/_helpers/checkUserIsLeagueOrganizer": typeof _model_leagueOrganizers__helpers_checkUserIsLeagueOrganizer;
  "_model/leagueOrganizers/_helpers/deepenLeagueOrganizer": typeof _model_leagueOrganizers__helpers_deepenLeagueOrganizer;
  "_model/leagueOrganizers/index": typeof _model_leagueOrganizers_index;
  "_model/leagueOrganizers/mutations/createLeagueOrganizer": typeof _model_leagueOrganizers_mutations_createLeagueOrganizer;
  "_model/leagueOrganizers/mutations/deleteLeagueOrganizer": typeof _model_leagueOrganizers_mutations_deleteLeagueOrganizer;
  "_model/leagueOrganizers/queries/getLeagueOrganizersByLeague": typeof _model_leagueOrganizers_queries_getLeagueOrganizersByLeague;
  "_model/leagueOrganizers/table": typeof _model_leagueOrganizers_table;
  "_model/leagueOrganizers/types": typeof _model_leagueOrganizers_types;
  "_model/leagueRankings/_helpers/deepenLeagueRanking": typeof _model_leagueRankings__helpers_deepenLeagueRanking;
  "_model/leagueRankings/index": typeof _model_leagueRankings_index;
  "_model/leagueRankings/mutations/refreshLeagueRanking": typeof _model_leagueRankings_mutations_refreshLeagueRanking;
  "_model/leagueRankings/queries/getLeagueRankingFullResults": typeof _model_leagueRankings_queries_getLeagueRankingFullResults;
  "_model/leagueRankings/queries/getLeagueRankingsByLeague": typeof _model_leagueRankings_queries_getLeagueRankingsByLeague;
  "_model/leagueRankings/table": typeof _model_leagueRankings_table;
  "_model/leagueRankings/types": typeof _model_leagueRankings_types;
  "_model/leagues/_helpers/calculateRankings": typeof _model_leagues__helpers_calculateRankings;
  "_model/leagues/_helpers/checkLeagueVisibility": typeof _model_leagues__helpers_checkLeagueVisibility;
  "_model/leagues/_helpers/deepenLeague": typeof _model_leagues__helpers_deepenLeague;
  "_model/leagues/index": typeof _model_leagues_index;
  "_model/leagues/mutations/createLeague": typeof _model_leagues_mutations_createLeague;
  "_model/leagues/mutations/refreshLeagueRankings": typeof _model_leagues_mutations_refreshLeagueRankings;
  "_model/leagues/queries/getLeague": typeof _model_leagues_queries_getLeague;
  "_model/leagues/queries/getLeagues": typeof _model_leagues_queries_getLeagues;
  "_model/leagues/table": typeof _model_leagues_table;
  "_model/leagues/types": typeof _model_leagues_types;
  "_model/lists/_helpers/deepenList": typeof _model_lists__helpers_deepenList;
  "_model/lists/actions/extractListData": typeof _model_lists_actions_extractListData;
  "_model/lists/actions/importList": typeof _model_lists_actions_importList;
  "_model/lists/index": typeof _model_lists_index;
  "_model/lists/mutations/createList": typeof _model_lists_mutations_createList;
  "_model/lists/queries/getList": typeof _model_lists_queries_getList;
  "_model/lists/table": typeof _model_lists_table;
  "_model/matchResultComments/_helpers/deepenMatchResultComment": typeof _model_matchResultComments__helpers_deepenMatchResultComment;
  "_model/matchResultComments/index": typeof _model_matchResultComments_index;
  "_model/matchResultComments/mutations/addMatchResultComment": typeof _model_matchResultComments_mutations_addMatchResultComment;
  "_model/matchResultComments/queries/getMatchResultComment": typeof _model_matchResultComments_queries_getMatchResultComment;
  "_model/matchResultComments/queries/getMatchResultCommentsByMatchResult": typeof _model_matchResultComments_queries_getMatchResultCommentsByMatchResult;
  "_model/matchResultComments/queries/getMatchResultCommentsByUser": typeof _model_matchResultComments_queries_getMatchResultCommentsByUser;
  "_model/matchResultComments/table": typeof _model_matchResultComments_table;
  "_model/matchResultLikes/_helpers/deepenMatchResultLike": typeof _model_matchResultLikes__helpers_deepenMatchResultLike;
  "_model/matchResultLikes/index": typeof _model_matchResultLikes_index;
  "_model/matchResultLikes/mutations/toggleMatchResultLike": typeof _model_matchResultLikes_mutations_toggleMatchResultLike;
  "_model/matchResultLikes/queries/getMatchResultLike": typeof _model_matchResultLikes_queries_getMatchResultLike;
  "_model/matchResultLikes/queries/getMatchResultLikesByMatchResult": typeof _model_matchResultLikes_queries_getMatchResultLikesByMatchResult;
  "_model/matchResultLikes/queries/getMatchResultLikesByUser": typeof _model_matchResultLikes_queries_getMatchResultLikesByUser;
  "_model/matchResultLikes/table": typeof _model_matchResultLikes_table;
  "_model/matchResults/_helpers/checkMatchResultAuth": typeof _model_matchResults__helpers_checkMatchResultAuth;
  "_model/matchResults/_helpers/checkMatchResultDetailsVisibility": typeof _model_matchResults__helpers_checkMatchResultDetailsVisibility;
  "_model/matchResults/_helpers/deepenMatchResult": typeof _model_matchResults__helpers_deepenMatchResult;
  "_model/matchResults/_helpers/deepenMatchResultDetails": typeof _model_matchResults__helpers_deepenMatchResultDetails;
  "_model/matchResults/_helpers/getShallowMatchResult": typeof _model_matchResults__helpers_getShallowMatchResult;
  "_model/matchResults/index": typeof _model_matchResults_index;
  "_model/matchResults/mutations/addPhotoToMatchResult": typeof _model_matchResults_mutations_addPhotoToMatchResult;
  "_model/matchResults/mutations/createMatchResult": typeof _model_matchResults_mutations_createMatchResult;
  "_model/matchResults/mutations/deleteMatchResult": typeof _model_matchResults_mutations_deleteMatchResult;
  "_model/matchResults/mutations/deleteMatchResultsByTournamentRound": typeof _model_matchResults_mutations_deleteMatchResultsByTournamentRound;
  "_model/matchResults/mutations/updateMatchResult": typeof _model_matchResults_mutations_updateMatchResult;
  "_model/matchResults/queries/getMatchResult": typeof _model_matchResults_queries_getMatchResult;
  "_model/matchResults/queries/getMatchResults": typeof _model_matchResults_queries_getMatchResults;
  "_model/matchResults/queries/getMatchResultsByTournament": typeof _model_matchResults_queries_getMatchResultsByTournament;
  "_model/matchResults/queries/getMatchResultsByTournamentPairing": typeof _model_matchResults_queries_getMatchResultsByTournamentPairing;
  "_model/matchResults/queries/getMatchResultsByTournamentRound": typeof _model_matchResults_queries_getMatchResultsByTournamentRound;
  "_model/matchResults/queries/getMatchResultsByUser": typeof _model_matchResults_queries_getMatchResultsByUser;
  "_model/matchResults/table": typeof _model_matchResults_table;
  "_model/matchResults/triggers": typeof _model_matchResults_triggers;
  "_model/photos/index": typeof _model_photos_index;
  "_model/photos/mutations/createPhoto": typeof _model_photos_mutations_createPhoto;
  "_model/photos/queries/getPhoto": typeof _model_photos_queries_getPhoto;
  "_model/photos/table": typeof _model_photos_table;
  "_model/tournamentCompetitors/_helpers/deepenTournamentCompetitor": typeof _model_tournamentCompetitors__helpers_deepenTournamentCompetitor;
  "_model/tournamentCompetitors/_helpers/getAvailableActions": typeof _model_tournamentCompetitors__helpers_getAvailableActions;
  "_model/tournamentCompetitors/_helpers/getDetails": typeof _model_tournamentCompetitors__helpers_getDetails;
  "_model/tournamentCompetitors/_helpers/getDisplayName": typeof _model_tournamentCompetitors__helpers_getDisplayName;
  "_model/tournamentCompetitors/_helpers/sortTournamentCompetitorsByName": typeof _model_tournamentCompetitors__helpers_sortTournamentCompetitorsByName;
  "_model/tournamentCompetitors/index": typeof _model_tournamentCompetitors_index;
  "_model/tournamentCompetitors/mutations/createTournamentCompetitor": typeof _model_tournamentCompetitors_mutations_createTournamentCompetitor;
  "_model/tournamentCompetitors/mutations/deleteTournamentCompetitor": typeof _model_tournamentCompetitors_mutations_deleteTournamentCompetitor;
  "_model/tournamentCompetitors/mutations/toggleTournamentCompetitorActive": typeof _model_tournamentCompetitors_mutations_toggleTournamentCompetitorActive;
  "_model/tournamentCompetitors/mutations/updateTournamentCompetitor": typeof _model_tournamentCompetitors_mutations_updateTournamentCompetitor;
  "_model/tournamentCompetitors/queries/getAvailableTournamentCompetitorActions": typeof _model_tournamentCompetitors_queries_getAvailableTournamentCompetitorActions;
  "_model/tournamentCompetitors/queries/getTournamentCompetitor": typeof _model_tournamentCompetitors_queries_getTournamentCompetitor;
  "_model/tournamentCompetitors/queries/getTournamentCompetitors": typeof _model_tournamentCompetitors_queries_getTournamentCompetitors;
  "_model/tournamentCompetitors/queries/getTournamentCompetitorsByTournament": typeof _model_tournamentCompetitors_queries_getTournamentCompetitorsByTournament;
  "_model/tournamentCompetitors/table": typeof _model_tournamentCompetitors_table;
  "_model/tournamentCompetitors/triggers": typeof _model_tournamentCompetitors_triggers;
  "_model/tournamentOrganizers/_helpers/checkUserIsTournamentOrganizer": typeof _model_tournamentOrganizers__helpers_checkUserIsTournamentOrganizer;
  "_model/tournamentOrganizers/_helpers/deepenTournamentOrganizer": typeof _model_tournamentOrganizers__helpers_deepenTournamentOrganizer;
  "_model/tournamentOrganizers/index": typeof _model_tournamentOrganizers_index;
  "_model/tournamentOrganizers/mutations/createTournamentOrganizer": typeof _model_tournamentOrganizers_mutations_createTournamentOrganizer;
  "_model/tournamentOrganizers/mutations/deleteTournamentOrganizer": typeof _model_tournamentOrganizers_mutations_deleteTournamentOrganizer;
  "_model/tournamentOrganizers/queries/getTournamentOrganizersByTournament": typeof _model_tournamentOrganizers_queries_getTournamentOrganizersByTournament;
  "_model/tournamentOrganizers/queries/getTournamentOrganizersByUser": typeof _model_tournamentOrganizers_queries_getTournamentOrganizersByUser;
  "_model/tournamentOrganizers/table": typeof _model_tournamentOrganizers_table;
  "_model/tournamentOrganizers/types": typeof _model_tournamentOrganizers_types;
  "_model/tournamentPairings/_helpers/assignBye": typeof _model_tournamentPairings__helpers_assignBye;
  "_model/tournamentPairings/_helpers/assignTables": typeof _model_tournamentPairings__helpers_assignTables;
  "_model/tournamentPairings/_helpers/checkIfPairingIsRepeat": typeof _model_tournamentPairings__helpers_checkIfPairingIsRepeat;
  "_model/tournamentPairings/_helpers/checkIfPairingIsSameAlignment": typeof _model_tournamentPairings__helpers_checkIfPairingIsSameAlignment;
  "_model/tournamentPairings/_helpers/deepenTournamentPairing": typeof _model_tournamentPairings__helpers_deepenTournamentPairing;
  "_model/tournamentPairings/_helpers/generateDraftPairings": typeof _model_tournamentPairings__helpers_generateDraftPairings;
  "_model/tournamentPairings/_helpers/getTournamentPairingDeep": typeof _model_tournamentPairings__helpers_getTournamentPairingDeep;
  "_model/tournamentPairings/_helpers/getTournamentPairingShallow": typeof _model_tournamentPairings__helpers_getTournamentPairingShallow;
  "_model/tournamentPairings/_helpers/getTournamentPairingUserIds": typeof _model_tournamentPairings__helpers_getTournamentPairingUserIds;
  "_model/tournamentPairings/_helpers/shuffle": typeof _model_tournamentPairings__helpers_shuffle;
  "_model/tournamentPairings/_helpers/sortByRank": typeof _model_tournamentPairings__helpers_sortByRank;
  "_model/tournamentPairings/_helpers/sortCompetitorPairs": typeof _model_tournamentPairings__helpers_sortCompetitorPairs;
  "_model/tournamentPairings/_helpers/sortPairingsByTable": typeof _model_tournamentPairings__helpers_sortPairingsByTable;
  "_model/tournamentPairings/_helpers/validateTournamentPairing": typeof _model_tournamentPairings__helpers_validateTournamentPairing;
  "_model/tournamentPairings/actions/generateDraftTournamentPairings": typeof _model_tournamentPairings_actions_generateDraftTournamentPairings;
  "_model/tournamentPairings/actions/generateTableAssignments": typeof _model_tournamentPairings_actions_generateTableAssignments;
  "_model/tournamentPairings/index": typeof _model_tournamentPairings_index;
  "_model/tournamentPairings/mutations/createTournamentPairings": typeof _model_tournamentPairings_mutations_createTournamentPairings;
  "_model/tournamentPairings/mutations/deleteTournamentPairings": typeof _model_tournamentPairings_mutations_deleteTournamentPairings;
  "_model/tournamentPairings/queries/getActiveTournamentPairingsByUser": typeof _model_tournamentPairings_queries_getActiveTournamentPairingsByUser;
  "_model/tournamentPairings/queries/getDraftTournamentPairings": typeof _model_tournamentPairings_queries_getDraftTournamentPairings;
  "_model/tournamentPairings/queries/getTournamentPairing": typeof _model_tournamentPairings_queries_getTournamentPairing;
  "_model/tournamentPairings/queries/getTournamentPairings": typeof _model_tournamentPairings_queries_getTournamentPairings;
  "_model/tournamentPairings/queries/getTournamentPairingsByTournament": typeof _model_tournamentPairings_queries_getTournamentPairingsByTournament;
  "_model/tournamentPairings/table": typeof _model_tournamentPairings_table;
  "_model/tournamentPairings/types": typeof _model_tournamentPairings_types;
  "_model/tournamentRegistrations/_helpers/checkUserIsRegistered": typeof _model_tournamentRegistrations__helpers_checkUserIsRegistered;
  "_model/tournamentRegistrations/_helpers/deepenTournamentRegistration": typeof _model_tournamentRegistrations__helpers_deepenTournamentRegistration;
  "_model/tournamentRegistrations/_helpers/getAvailableActions": typeof _model_tournamentRegistrations__helpers_getAvailableActions;
  "_model/tournamentRegistrations/_helpers/getCreateSuccessMessage": typeof _model_tournamentRegistrations__helpers_getCreateSuccessMessage;
  "_model/tournamentRegistrations/_helpers/getDeleteSuccessMessage": typeof _model_tournamentRegistrations__helpers_getDeleteSuccessMessage;
  "_model/tournamentRegistrations/index": typeof _model_tournamentRegistrations_index;
  "_model/tournamentRegistrations/mutations/createTournamentRegistration": typeof _model_tournamentRegistrations_mutations_createTournamentRegistration;
  "_model/tournamentRegistrations/mutations/deleteTournamentRegistration": typeof _model_tournamentRegistrations_mutations_deleteTournamentRegistration;
  "_model/tournamentRegistrations/mutations/toggleTournamentRegistrationActive": typeof _model_tournamentRegistrations_mutations_toggleTournamentRegistrationActive;
  "_model/tournamentRegistrations/mutations/updateTournamentRegistration": typeof _model_tournamentRegistrations_mutations_updateTournamentRegistration;
  "_model/tournamentRegistrations/queries/getTournamentRegistrationByTournamentUser": typeof _model_tournamentRegistrations_queries_getTournamentRegistrationByTournamentUser;
  "_model/tournamentRegistrations/queries/getTournamentRegistrationsByCompetitor": typeof _model_tournamentRegistrations_queries_getTournamentRegistrationsByCompetitor;
  "_model/tournamentRegistrations/queries/getTournamentRegistrationsByTournament": typeof _model_tournamentRegistrations_queries_getTournamentRegistrationsByTournament;
  "_model/tournamentRegistrations/queries/getTournamentRegistrationsByUser": typeof _model_tournamentRegistrations_queries_getTournamentRegistrationsByUser;
  "_model/tournamentRegistrations/table": typeof _model_tournamentRegistrations_table;
  "_model/tournamentRegistrations/types": typeof _model_tournamentRegistrations_types;
  "_model/tournamentResults/_helpers/aggregateTournamentData": typeof _model_tournamentResults__helpers_aggregateTournamentData;
  "_model/tournamentResults/_helpers/applyScoreAdjustments": typeof _model_tournamentResults__helpers_applyScoreAdjustments;
  "_model/tournamentResults/index": typeof _model_tournamentResults_index;
  "_model/tournamentResults/mutations/refreshTournamentResult": typeof _model_tournamentResults_mutations_refreshTournamentResult;
  "_model/tournamentResults/queries/getTournamentResultsByCompetitor": typeof _model_tournamentResults_queries_getTournamentResultsByCompetitor;
  "_model/tournamentResults/queries/getTournamentResultsByGameSystem": typeof _model_tournamentResults_queries_getTournamentResultsByGameSystem;
  "_model/tournamentResults/queries/getTournamentResultsByRound": typeof _model_tournamentResults_queries_getTournamentResultsByRound;
  "_model/tournamentResults/queries/getTournamentResultsByUser": typeof _model_tournamentResults_queries_getTournamentResultsByUser;
  "_model/tournamentResults/table": typeof _model_tournamentResults_table;
  "_model/tournamentResults/triggers": typeof _model_tournamentResults_triggers;
  "_model/tournamentResults/types": typeof _model_tournamentResults_types;
  "_model/tournamentTimers/_helpers/convertRoundStructureToMs": typeof _model_tournamentTimers__helpers_convertRoundStructureToMs;
  "_model/tournamentTimers/_helpers/deepenTournamentTimer": typeof _model_tournamentTimers__helpers_deepenTournamentTimer;
  "_model/tournamentTimers/_helpers/getTournamentTimerShallow": typeof _model_tournamentTimers__helpers_getTournamentTimerShallow;
  "_model/tournamentTimers/index": typeof _model_tournamentTimers_index;
  "_model/tournamentTimers/mutations/createTournamentTimer": typeof _model_tournamentTimers_mutations_createTournamentTimer;
  "_model/tournamentTimers/mutations/deleteTournamentTimerByTournament": typeof _model_tournamentTimers_mutations_deleteTournamentTimerByTournament;
  "_model/tournamentTimers/mutations/resetTournamentTimer": typeof _model_tournamentTimers_mutations_resetTournamentTimer;
  "_model/tournamentTimers/mutations/setTournamentTimerPhase": typeof _model_tournamentTimers_mutations_setTournamentTimerPhase;
  "_model/tournamentTimers/mutations/toggleTournamentTimer": typeof _model_tournamentTimers_mutations_toggleTournamentTimer;
  "_model/tournamentTimers/queries/getTournamentTimer": typeof _model_tournamentTimers_queries_getTournamentTimer;
  "_model/tournamentTimers/queries/getTournamentTimerByTournament": typeof _model_tournamentTimers_queries_getTournamentTimerByTournament;
  "_model/tournamentTimers/table": typeof _model_tournamentTimers_table;
  "_model/tournaments/_helpers/checkTournamentAuth": typeof _model_tournaments__helpers_checkTournamentAuth;
  "_model/tournaments/_helpers/checkTournamentVisibility": typeof _model_tournaments__helpers_checkTournamentVisibility;
  "_model/tournaments/_helpers/deepenTournament": typeof _model_tournaments__helpers_deepenTournament;
  "_model/tournaments/_helpers/extractSearchTokens": typeof _model_tournaments__helpers_extractSearchTokens;
  "_model/tournaments/_helpers/getAvailableActions": typeof _model_tournaments__helpers_getAvailableActions;
  "_model/tournaments/_helpers/getDisplayName": typeof _model_tournaments__helpers_getDisplayName;
  "_model/tournaments/_helpers/getTournamentDeep": typeof _model_tournaments__helpers_getTournamentDeep;
  "_model/tournaments/_helpers/getTournamentNextRound": typeof _model_tournaments__helpers_getTournamentNextRound;
  "_model/tournaments/_helpers/getTournamentPlayerUserIds": typeof _model_tournaments__helpers_getTournamentPlayerUserIds;
  "_model/tournaments/_helpers/getTournamentShallow": typeof _model_tournaments__helpers_getTournamentShallow;
  "_model/tournaments/actions/exportFowV4TournamentMatchData": typeof _model_tournaments_actions_exportFowV4TournamentMatchData;
  "_model/tournaments/index": typeof _model_tournaments_index;
  "_model/tournaments/mutations/createTournament": typeof _model_tournaments_mutations_createTournament;
  "_model/tournaments/mutations/deleteTournament": typeof _model_tournaments_mutations_deleteTournament;
  "_model/tournaments/mutations/endTournament": typeof _model_tournaments_mutations_endTournament;
  "_model/tournaments/mutations/endTournamentRound": typeof _model_tournaments_mutations_endTournamentRound;
  "_model/tournaments/mutations/publishTournament": typeof _model_tournaments_mutations_publishTournament;
  "_model/tournaments/mutations/startTournament": typeof _model_tournaments_mutations_startTournament;
  "_model/tournaments/mutations/startTournamentRound": typeof _model_tournaments_mutations_startTournamentRound;
  "_model/tournaments/mutations/toggleTournamentAlignmentsRevealed": typeof _model_tournaments_mutations_toggleTournamentAlignmentsRevealed;
  "_model/tournaments/mutations/updateTournament": typeof _model_tournaments_mutations_updateTournament;
  "_model/tournaments/queries/getTournament": typeof _model_tournaments_queries_getTournament;
  "_model/tournaments/queries/getTournamentByTournamentPairing": typeof _model_tournaments_queries_getTournamentByTournamentPairing;
  "_model/tournaments/queries/getTournamentOpenRound": typeof _model_tournaments_queries_getTournamentOpenRound;
  "_model/tournaments/queries/getTournaments": typeof _model_tournaments_queries_getTournaments;
  "_model/tournaments/table": typeof _model_tournaments_table;
  "_model/userPreferences/index": typeof _model_userPreferences_index;
  "_model/userPreferences/mutations": typeof _model_userPreferences_mutations;
  "_model/userPreferences/queries": typeof _model_userPreferences_queries;
  "_model/userPreferences/table": typeof _model_userPreferences_table;
  "_model/users/_helpers/checkUserAuth": typeof _model_users__helpers_checkUserAuth;
  "_model/users/_helpers/checkUserRelationshipLevel": typeof _model_users__helpers_checkUserRelationshipLevel;
  "_model/users/_helpers/checkUserTournamentRelationship": typeof _model_users__helpers_checkUserTournamentRelationship;
  "_model/users/_helpers/createClaimToken": typeof _model_users__helpers_createClaimToken;
  "_model/users/_helpers/extractSearchTokens": typeof _model_users__helpers_extractSearchTokens;
  "_model/users/_helpers/formatUserRealName": typeof _model_users__helpers_formatUserRealName;
  "_model/users/_helpers/generateUsername": typeof _model_users__helpers_generateUsername;
  "_model/users/_helpers/getShallowUser": typeof _model_users__helpers_getShallowUser;
  "_model/users/_helpers/hashClaimToken": typeof _model_users__helpers_hashClaimToken;
  "_model/users/_helpers/redactUser": typeof _model_users__helpers_redactUser;
  "_model/users/actions/claimUser": typeof _model_users_actions_claimUser;
  "_model/users/actions/internal/addContactToResend": typeof _model_users_actions_internal_addContactToResend;
  "_model/users/actions/internal/setUserDefaultAvatar": typeof _model_users_actions_internal_setUserDefaultAvatar;
  "_model/users/actions/inviteUser": typeof _model_users_actions_inviteUser;
  "_model/users/index": typeof _model_users_index;
  "_model/users/mutations/internal/deleteUserClaimToken": typeof _model_users_mutations_internal_deleteUserClaimToken;
  "_model/users/mutations/internal/updateUserClaimToken": typeof _model_users_mutations_internal_updateUserClaimToken;
  "_model/users/mutations/updateUser": typeof _model_users_mutations_updateUser;
  "_model/users/mutations/updateUserAvatar": typeof _model_users_mutations_updateUserAvatar;
  "_model/users/mutations/updateUserAvatarNoAuth": typeof _model_users_mutations_updateUserAvatarNoAuth;
  "_model/users/queries/getCurrentUser": typeof _model_users_queries_getCurrentUser;
  "_model/users/queries/getUser": typeof _model_users_queries_getUser;
  "_model/users/queries/getUsers": typeof _model_users_queries_getUsers;
  "_model/users/queries/internal/getUserByClaimToken": typeof _model_users_queries_internal_getUserByClaimToken;
  "_model/users/queries/internal/getUserByEmail": typeof _model_users_queries_internal_getUserByEmail;
  "_model/users/table": typeof _model_users_table;
  "_model/utils/_helpers/testUsers": typeof _model_utils__helpers_testUsers;
  "_model/utils/actions/populateUsers": typeof _model_utils_actions_populateUsers;
  "_model/utils/createTestTournament": typeof _model_utils_createTestTournament;
  "_model/utils/createTestTournamentMatchResults": typeof _model_utils_createTestTournamentMatchResults;
  "_model/utils/createTestUsers": typeof _model_utils_createTestUsers;
  "_model/utils/deleteTestTournament": typeof _model_utils_deleteTestTournament;
  "_model/utils/index": typeof _model_utils_index;
  "_model/utils/mergeUser": typeof _model_utils_mergeUser;
  "_model/utils/mutations/refreshSearchIndex": typeof _model_utils_mutations_refreshSearchIndex;
  "_model/utils/mutations/revealTournamentPlayerNames": typeof _model_utils_mutations_revealTournamentPlayerNames;
  auth: typeof auth;
  crons: typeof crons;
  "emails/InviteUserEmail": typeof emails_InviteUserEmail;
  "emails/PasswordResetEmail": typeof emails_PasswordResetEmail;
  "emails/Wrapper": typeof emails_Wrapper;
  "emails/styles": typeof emails_styles;
  files: typeof files;
  friendships: typeof friendships;
  functions: typeof functions;
  generateFileUploadUrl: typeof generateFileUploadUrl;
  http: typeof http;
  leagueRankings: typeof leagueRankings;
  leagues: typeof leagues;
  lists: typeof lists;
  matchResultComments: typeof matchResultComments;
  matchResultLikes: typeof matchResultLikes;
  matchResults: typeof matchResults;
  migrations: typeof migrations;
  photos: typeof photos;
  scheduledTasks: typeof scheduledTasks;
  tournamentCompetitors: typeof tournamentCompetitors;
  tournamentPairings: typeof tournamentPairings;
  tournamentRegistrations: typeof tournamentRegistrations;
  tournamentResults: typeof tournamentResults;
  tournamentTimers: typeof tournamentTimers;
  tournaments: typeof tournaments;
  userPreferences: typeof userPreferences;
  users: typeof users;
  utils: typeof utils;
}>;
declare const fullApiWithMounts: typeof fullApi;

export declare const api: FilterApi<
  typeof fullApiWithMounts,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApiWithMounts,
  FunctionReference<any, "internal">
>;

export declare const components: {
  migrations: {
    lib: {
      cancel: FunctionReference<
        "mutation",
        "internal",
        { name: string },
        {
          batchSize?: number;
          cursor?: string | null;
          error?: string;
          isDone: boolean;
          latestEnd?: number;
          latestStart: number;
          name: string;
          next?: Array<string>;
          processed: number;
          state: "inProgress" | "success" | "failed" | "canceled" | "unknown";
        }
      >;
      cancelAll: FunctionReference<
        "mutation",
        "internal",
        { sinceTs?: number },
        Array<{
          batchSize?: number;
          cursor?: string | null;
          error?: string;
          isDone: boolean;
          latestEnd?: number;
          latestStart: number;
          name: string;
          next?: Array<string>;
          processed: number;
          state: "inProgress" | "success" | "failed" | "canceled" | "unknown";
        }>
      >;
      clearAll: FunctionReference<
        "mutation",
        "internal",
        { before?: number },
        null
      >;
      getStatus: FunctionReference<
        "query",
        "internal",
        { limit?: number; names?: Array<string> },
        Array<{
          batchSize?: number;
          cursor?: string | null;
          error?: string;
          isDone: boolean;
          latestEnd?: number;
          latestStart: number;
          name: string;
          next?: Array<string>;
          processed: number;
          state: "inProgress" | "success" | "failed" | "canceled" | "unknown";
        }>
      >;
      migrate: FunctionReference<
        "mutation",
        "internal",
        {
          batchSize?: number;
          cursor?: string | null;
          dryRun: boolean;
          fnHandle: string;
          name: string;
          next?: Array<{ fnHandle: string; name: string }>;
        },
        {
          batchSize?: number;
          cursor?: string | null;
          error?: string;
          isDone: boolean;
          latestEnd?: number;
          latestStart: number;
          name: string;
          next?: Array<string>;
          processed: number;
          state: "inProgress" | "success" | "failed" | "canceled" | "unknown";
        }
      >;
    };
  };
};
