/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as _model__helpers_clamp from "../_model/_helpers/clamp.js";
import type * as _model__helpers_filterWithSearchTerm from "../_model/_helpers/filterWithSearchTerm.js";
import type * as _model__helpers_getRange from "../_model/_helpers/getRange.js";
import type * as _model__helpers_getStorageUrl from "../_model/_helpers/getStorageUrl.js";
import type * as _model__helpers_notNullOrUndefined from "../_model/_helpers/notNullOrUndefined.js";
import type * as _model_fowV4_aggregateFowV4TournamentData from "../_model/fowV4/aggregateFowV4TournamentData.js";
import type * as _model_fowV4_calculateFowV4MatchResultScore from "../_model/fowV4/calculateFowV4MatchResultScore.js";
import type * as _model_fowV4_calculateFowV4TournamentRankings from "../_model/fowV4/calculateFowV4TournamentRankings.js";
import type * as _model_fowV4_createFowV4TournamentExtendedStatMap from "../_model/fowV4/createFowV4TournamentExtendedStatMap.js";
import type * as _model_fowV4_createTournamentCompetitorMetaMap from "../_model/fowV4/createTournamentCompetitorMetaMap.js";
import type * as _model_fowV4_divideFowV4BaseStats from "../_model/fowV4/divideFowV4BaseStats.js";
import type * as _model_fowV4_extractFowV4MatchResultBaseStats from "../_model/fowV4/extractFowV4MatchResultBaseStats.js";
import type * as _model_fowV4_flattenFowV4StatMap from "../_model/fowV4/flattenFowV4StatMap.js";
import type * as _model_fowV4_sumFowV4BaseStats from "../_model/fowV4/sumFowV4BaseStats.js";
import type * as _model_fowV4_types from "../_model/fowV4/types.js";
import type * as _model_matchResults_getDeepMatchResult from "../_model/matchResults/getDeepMatchResult.js";
import type * as _model_matchResults_getMatchResultsByTournament from "../_model/matchResults/getMatchResultsByTournament.js";
import type * as _model_matchResults_getMatchResultsByTournamentPairing from "../_model/matchResults/getMatchResultsByTournamentPairing.js";
import type * as _model_matchResults_getMatchResultsByTournamentRound from "../_model/matchResults/getMatchResultsByTournamentRound.js";
import type * as _model_matchResults_helpers from "../_model/matchResults/helpers.js";
import type * as _model_tournamentCompetitors_fields from "../_model/tournamentCompetitors/fields.js";
import type * as _model_tournamentCompetitors_helpers from "../_model/tournamentCompetitors/helpers.js";
import type * as _model_tournamentCompetitors_index from "../_model/tournamentCompetitors/index.js";
import type * as _model_tournamentCompetitors_mutations from "../_model/tournamentCompetitors/mutations.js";
import type * as _model_tournamentCompetitors_queries from "../_model/tournamentCompetitors/queries.js";
import type * as _model_tournamentPairings__helpers_assignBye from "../_model/tournamentPairings/_helpers/assignBye.js";
import type * as _model_tournamentPairings__helpers_deepenTournamentPairing from "../_model/tournamentPairings/_helpers/deepenTournamentPairing.js";
import type * as _model_tournamentPairings__helpers_generateDraftPairings from "../_model/tournamentPairings/_helpers/generateDraftPairings.js";
import type * as _model_tournamentPairings__helpers_generateTableAssignments from "../_model/tournamentPairings/_helpers/generateTableAssignments.js";
import type * as _model_tournamentPairings__helpers_getTournamentPairingDeep from "../_model/tournamentPairings/_helpers/getTournamentPairingDeep.js";
import type * as _model_tournamentPairings__helpers_getTournamentPairingShallow from "../_model/tournamentPairings/_helpers/getTournamentPairingShallow.js";
import type * as _model_tournamentPairings__helpers_shuffle from "../_model/tournamentPairings/_helpers/shuffle.js";
import type * as _model_tournamentPairings__helpers_sortByRank from "../_model/tournamentPairings/_helpers/sortByRank.js";
import type * as _model_tournamentPairings_fields from "../_model/tournamentPairings/fields.js";
import type * as _model_tournamentPairings_index from "../_model/tournamentPairings/index.js";
import type * as _model_tournamentPairings_queries_getActiveTournamentPairingsByUser from "../_model/tournamentPairings/queries/getActiveTournamentPairingsByUser.js";
import type * as _model_tournamentPairings_queries_getDraftTournamentPairings from "../_model/tournamentPairings/queries/getDraftTournamentPairings.js";
import type * as _model_tournamentPairings_queries_getTournamentPairing from "../_model/tournamentPairings/queries/getTournamentPairing.js";
import type * as _model_tournamentPairings_queries_getTournamentPairings from "../_model/tournamentPairings/queries/getTournamentPairings.js";
import type * as _model_tournamentPairings_queries_getTournamentPairingsByTournament from "../_model/tournamentPairings/queries/getTournamentPairingsByTournament.js";
import type * as _model_tournamentTimers__helpers_convertRoundStructureToMs from "../_model/tournamentTimers/_helpers/convertRoundStructureToMs.js";
import type * as _model_tournamentTimers__helpers_deepenTournamentTimer from "../_model/tournamentTimers/_helpers/deepenTournamentTimer.js";
import type * as _model_tournamentTimers__helpers_getTournamentTimerShallow from "../_model/tournamentTimers/_helpers/getTournamentTimerShallow.js";
import type * as _model_tournamentTimers_fields from "../_model/tournamentTimers/fields.js";
import type * as _model_tournamentTimers_index from "../_model/tournamentTimers/index.js";
import type * as _model_tournamentTimers_mutations_createTournamentTimer from "../_model/tournamentTimers/mutations/createTournamentTimer.js";
import type * as _model_tournamentTimers_mutations_deleteTournamentTimerByTournament from "../_model/tournamentTimers/mutations/deleteTournamentTimerByTournament.js";
import type * as _model_tournamentTimers_mutations_resetTournamentTimer from "../_model/tournamentTimers/mutations/resetTournamentTimer.js";
import type * as _model_tournamentTimers_mutations_setTournamentTimerPhase from "../_model/tournamentTimers/mutations/setTournamentTimerPhase.js";
import type * as _model_tournamentTimers_mutations_toggleTournamentTimer from "../_model/tournamentTimers/mutations/toggleTournamentTimer.js";
import type * as _model_tournamentTimers_queries_getTournamentTimer from "../_model/tournamentTimers/queries/getTournamentTimer.js";
import type * as _model_tournamentTimers_queries_getTournamentTimerByTournament from "../_model/tournamentTimers/queries/getTournamentTimerByTournament.js";
import type * as _model_tournaments__helpers_checkTournamentAuth from "../_model/tournaments/_helpers/checkTournamentAuth.js";
import type * as _model_tournaments__helpers_checkTournamentVisibility from "../_model/tournaments/_helpers/checkTournamentVisibility.js";
import type * as _model_tournaments__helpers_deepenTournament from "../_model/tournaments/_helpers/deepenTournament.js";
import type * as _model_tournaments__helpers_getTournamentDeep from "../_model/tournaments/_helpers/getTournamentDeep.js";
import type * as _model_tournaments__helpers_getTournamentShallow from "../_model/tournaments/_helpers/getTournamentShallow.js";
import type * as _model_tournaments__helpers_getTournamentUserIds from "../_model/tournaments/_helpers/getTournamentUserIds.js";
import type * as _model_tournaments_fields from "../_model/tournaments/fields.js";
import type * as _model_tournaments_index from "../_model/tournaments/index.js";
import type * as _model_tournaments_mutations_closeTournamentRound from "../_model/tournaments/mutations/closeTournamentRound.js";
import type * as _model_tournaments_mutations_createTournament from "../_model/tournaments/mutations/createTournament.js";
import type * as _model_tournaments_mutations_deleteTournament from "../_model/tournaments/mutations/deleteTournament.js";
import type * as _model_tournaments_mutations_endTournament from "../_model/tournaments/mutations/endTournament.js";
import type * as _model_tournaments_mutations_openTournamentRound from "../_model/tournaments/mutations/openTournamentRound.js";
import type * as _model_tournaments_mutations_publishTournament from "../_model/tournaments/mutations/publishTournament.js";
import type * as _model_tournaments_mutations_startTournament from "../_model/tournaments/mutations/startTournament.js";
import type * as _model_tournaments_mutations_updateTournament from "../_model/tournaments/mutations/updateTournament.js";
import type * as _model_tournaments_queries_getTournament from "../_model/tournaments/queries/getTournament.js";
import type * as _model_tournaments_queries_getTournamentOpenRound from "../_model/tournaments/queries/getTournamentOpenRound.js";
import type * as _model_tournaments_queries_getTournamentRankings from "../_model/tournaments/queries/getTournamentRankings.js";
import type * as _model_tournaments_queries_getTournaments from "../_model/tournaments/queries/getTournaments.js";
import type * as _model_tournaments_queries_getTournamentsByStatus from "../_model/tournaments/queries/getTournamentsByStatus.js";
import type * as _model_utils__helpers_mockData from "../_model/utils/_helpers/mockData.js";
import type * as _model_utils__helpers_testUsers from "../_model/utils/_helpers/testUsers.js";
import type * as _model_utils_createTestTournament from "../_model/utils/createTestTournament.js";
import type * as _model_utils_createTestTournamentMatchResults from "../_model/utils/createTestTournamentMatchResults.js";
import type * as _model_utils_deleteTestTournament from "../_model/utils/deleteTestTournament.js";
import type * as _model_utils_index from "../_model/utils/index.js";
import type * as auth_ResendOtpPasswordReset from "../auth/ResendOtpPasswordReset.js";
import type * as auth_ResendOtpVerification from "../auth/ResendOtpVerification.js";
import type * as auth from "../auth.js";
import type * as common_errors from "../common/errors.js";
import type * as common_fowV4_fowV4GameSystemConfig from "../common/fowV4/fowV4GameSystemConfig.js";
import type * as common_fowV4_fowV4MatchOutcomeType from "../common/fowV4/fowV4MatchOutcomeType.js";
import type * as common_fowV4_fowV4MatchResultDetails from "../common/fowV4/fowV4MatchResultDetails.js";
import type * as common_fowV4_getMission from "../common/fowV4/getMission.js";
import type * as common_fowV4_getMissionPack from "../common/fowV4/getMissionPack.js";
import type * as common_location from "../common/location.js";
import type * as common_tournamentStatus from "../common/tournamentStatus.js";
import type * as common_userDataVisibilityLevel from "../common/userDataVisibilityLevel.js";
import type * as friendships_confirmFriendship from "../friendships/confirmFriendship.js";
import type * as friendships_createFriendship from "../friendships/createFriendship.js";
import type * as friendships_deleteFriendship from "../friendships/deleteFriendship.js";
import type * as friendships_fetchFriendship from "../friendships/fetchFriendship.js";
import type * as friendships_fetchFriendshipRequests from "../friendships/fetchFriendshipRequests.js";
import type * as friendships_fetchFriendshipUserIdsByUserId from "../friendships/fetchFriendshipUserIdsByUserId.js";
import type * as friendships_index from "../friendships/index.js";
import type * as generateFileUploadUrl from "../generateFileUploadUrl.js";
import type * as http from "../http.js";
import type * as matchResultComments_index from "../matchResultComments/index.js";
import type * as matchResultComments_mutations from "../matchResultComments/mutations.js";
import type * as matchResultComments_queries from "../matchResultComments/queries.js";
import type * as matchResultLikes_index from "../matchResultLikes/index.js";
import type * as matchResultLikes_mutations from "../matchResultLikes/mutations.js";
import type * as matchResultLikes_queries from "../matchResultLikes/queries.js";
import type * as matchResults_fetchMatchResult from "../matchResults/fetchMatchResult.js";
import type * as matchResults_fetchMatchResultList from "../matchResults/fetchMatchResultList.js";
import type * as matchResults_index from "../matchResults/index.js";
import type * as matchResults_mutations from "../matchResults/mutations.js";
import type * as photos_index from "../photos/index.js";
import type * as photos_mutations from "../photos/mutations.js";
import type * as photos_queries from "../photos/queries.js";
import type * as static_currencyCodes from "../static/currencyCodes.js";
import type * as static_fowV4_dynamicPointsVersions from "../static/fowV4/dynamicPointsVersions.js";
import type * as static_fowV4_eras from "../static/fowV4/eras.js";
import type * as static_fowV4_factions from "../static/fowV4/factions.js";
import type * as static_fowV4_fowV4BattlePlan from "../static/fowV4/fowV4BattlePlan.js";
import type * as static_fowV4_fowV4RankingFactors from "../static/fowV4/fowV4RankingFactors.js";
import type * as static_fowV4_lessonsFromTheFrontVersions from "../static/fowV4/lessonsFromTheFrontVersions.js";
import type * as static_fowV4_missionPacks from "../static/fowV4/missionPacks.js";
import type * as static_gameSystems from "../static/gameSystems.js";
import type * as static_tournamentPairingMethods from "../static/tournamentPairingMethods.js";
import type * as static_tournamentPhases from "../static/tournamentPhases.js";
import type * as tournamentCompetitors from "../tournamentCompetitors.js";
import type * as tournamentPairings from "../tournamentPairings.js";
import type * as tournamentTimers from "../tournamentTimers.js";
import type * as tournaments from "../tournaments.js";
import type * as users_checkUsernameExists from "../users/checkUsernameExists.js";
import type * as users_fetchCurrentUser from "../users/fetchCurrentUser.js";
import type * as users_fetchUser from "../users/fetchUser.js";
import type * as users_fetchUserList from "../users/fetchUserList.js";
import type * as users_index from "../users/index.js";
import type * as users_updateAvatar from "../users/updateAvatar.js";
import type * as users_updateUser from "../users/updateUser.js";
import type * as users_utils_checkUserTournamentRelationship from "../users/utils/checkUserTournamentRelationship.js";
import type * as users_utils_getAvatarUrl from "../users/utils/getAvatarUrl.js";
import type * as users_utils_getLimitedUser from "../users/utils/getLimitedUser.js";
import type * as users_utils_redactUserInfo from "../users/utils/redactUserInfo.js";
import type * as utils from "../utils.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "_model/_helpers/clamp": typeof _model__helpers_clamp;
  "_model/_helpers/filterWithSearchTerm": typeof _model__helpers_filterWithSearchTerm;
  "_model/_helpers/getRange": typeof _model__helpers_getRange;
  "_model/_helpers/getStorageUrl": typeof _model__helpers_getStorageUrl;
  "_model/_helpers/notNullOrUndefined": typeof _model__helpers_notNullOrUndefined;
  "_model/fowV4/aggregateFowV4TournamentData": typeof _model_fowV4_aggregateFowV4TournamentData;
  "_model/fowV4/calculateFowV4MatchResultScore": typeof _model_fowV4_calculateFowV4MatchResultScore;
  "_model/fowV4/calculateFowV4TournamentRankings": typeof _model_fowV4_calculateFowV4TournamentRankings;
  "_model/fowV4/createFowV4TournamentExtendedStatMap": typeof _model_fowV4_createFowV4TournamentExtendedStatMap;
  "_model/fowV4/createTournamentCompetitorMetaMap": typeof _model_fowV4_createTournamentCompetitorMetaMap;
  "_model/fowV4/divideFowV4BaseStats": typeof _model_fowV4_divideFowV4BaseStats;
  "_model/fowV4/extractFowV4MatchResultBaseStats": typeof _model_fowV4_extractFowV4MatchResultBaseStats;
  "_model/fowV4/flattenFowV4StatMap": typeof _model_fowV4_flattenFowV4StatMap;
  "_model/fowV4/sumFowV4BaseStats": typeof _model_fowV4_sumFowV4BaseStats;
  "_model/fowV4/types": typeof _model_fowV4_types;
  "_model/matchResults/getDeepMatchResult": typeof _model_matchResults_getDeepMatchResult;
  "_model/matchResults/getMatchResultsByTournament": typeof _model_matchResults_getMatchResultsByTournament;
  "_model/matchResults/getMatchResultsByTournamentPairing": typeof _model_matchResults_getMatchResultsByTournamentPairing;
  "_model/matchResults/getMatchResultsByTournamentRound": typeof _model_matchResults_getMatchResultsByTournamentRound;
  "_model/matchResults/helpers": typeof _model_matchResults_helpers;
  "_model/tournamentCompetitors/fields": typeof _model_tournamentCompetitors_fields;
  "_model/tournamentCompetitors/helpers": typeof _model_tournamentCompetitors_helpers;
  "_model/tournamentCompetitors/index": typeof _model_tournamentCompetitors_index;
  "_model/tournamentCompetitors/mutations": typeof _model_tournamentCompetitors_mutations;
  "_model/tournamentCompetitors/queries": typeof _model_tournamentCompetitors_queries;
  "_model/tournamentPairings/_helpers/assignBye": typeof _model_tournamentPairings__helpers_assignBye;
  "_model/tournamentPairings/_helpers/deepenTournamentPairing": typeof _model_tournamentPairings__helpers_deepenTournamentPairing;
  "_model/tournamentPairings/_helpers/generateDraftPairings": typeof _model_tournamentPairings__helpers_generateDraftPairings;
  "_model/tournamentPairings/_helpers/generateTableAssignments": typeof _model_tournamentPairings__helpers_generateTableAssignments;
  "_model/tournamentPairings/_helpers/getTournamentPairingDeep": typeof _model_tournamentPairings__helpers_getTournamentPairingDeep;
  "_model/tournamentPairings/_helpers/getTournamentPairingShallow": typeof _model_tournamentPairings__helpers_getTournamentPairingShallow;
  "_model/tournamentPairings/_helpers/shuffle": typeof _model_tournamentPairings__helpers_shuffle;
  "_model/tournamentPairings/_helpers/sortByRank": typeof _model_tournamentPairings__helpers_sortByRank;
  "_model/tournamentPairings/fields": typeof _model_tournamentPairings_fields;
  "_model/tournamentPairings/index": typeof _model_tournamentPairings_index;
  "_model/tournamentPairings/queries/getActiveTournamentPairingsByUser": typeof _model_tournamentPairings_queries_getActiveTournamentPairingsByUser;
  "_model/tournamentPairings/queries/getDraftTournamentPairings": typeof _model_tournamentPairings_queries_getDraftTournamentPairings;
  "_model/tournamentPairings/queries/getTournamentPairing": typeof _model_tournamentPairings_queries_getTournamentPairing;
  "_model/tournamentPairings/queries/getTournamentPairings": typeof _model_tournamentPairings_queries_getTournamentPairings;
  "_model/tournamentPairings/queries/getTournamentPairingsByTournament": typeof _model_tournamentPairings_queries_getTournamentPairingsByTournament;
  "_model/tournamentTimers/_helpers/convertRoundStructureToMs": typeof _model_tournamentTimers__helpers_convertRoundStructureToMs;
  "_model/tournamentTimers/_helpers/deepenTournamentTimer": typeof _model_tournamentTimers__helpers_deepenTournamentTimer;
  "_model/tournamentTimers/_helpers/getTournamentTimerShallow": typeof _model_tournamentTimers__helpers_getTournamentTimerShallow;
  "_model/tournamentTimers/fields": typeof _model_tournamentTimers_fields;
  "_model/tournamentTimers/index": typeof _model_tournamentTimers_index;
  "_model/tournamentTimers/mutations/createTournamentTimer": typeof _model_tournamentTimers_mutations_createTournamentTimer;
  "_model/tournamentTimers/mutations/deleteTournamentTimerByTournament": typeof _model_tournamentTimers_mutations_deleteTournamentTimerByTournament;
  "_model/tournamentTimers/mutations/resetTournamentTimer": typeof _model_tournamentTimers_mutations_resetTournamentTimer;
  "_model/tournamentTimers/mutations/setTournamentTimerPhase": typeof _model_tournamentTimers_mutations_setTournamentTimerPhase;
  "_model/tournamentTimers/mutations/toggleTournamentTimer": typeof _model_tournamentTimers_mutations_toggleTournamentTimer;
  "_model/tournamentTimers/queries/getTournamentTimer": typeof _model_tournamentTimers_queries_getTournamentTimer;
  "_model/tournamentTimers/queries/getTournamentTimerByTournament": typeof _model_tournamentTimers_queries_getTournamentTimerByTournament;
  "_model/tournaments/_helpers/checkTournamentAuth": typeof _model_tournaments__helpers_checkTournamentAuth;
  "_model/tournaments/_helpers/checkTournamentVisibility": typeof _model_tournaments__helpers_checkTournamentVisibility;
  "_model/tournaments/_helpers/deepenTournament": typeof _model_tournaments__helpers_deepenTournament;
  "_model/tournaments/_helpers/getTournamentDeep": typeof _model_tournaments__helpers_getTournamentDeep;
  "_model/tournaments/_helpers/getTournamentShallow": typeof _model_tournaments__helpers_getTournamentShallow;
  "_model/tournaments/_helpers/getTournamentUserIds": typeof _model_tournaments__helpers_getTournamentUserIds;
  "_model/tournaments/fields": typeof _model_tournaments_fields;
  "_model/tournaments/index": typeof _model_tournaments_index;
  "_model/tournaments/mutations/closeTournamentRound": typeof _model_tournaments_mutations_closeTournamentRound;
  "_model/tournaments/mutations/createTournament": typeof _model_tournaments_mutations_createTournament;
  "_model/tournaments/mutations/deleteTournament": typeof _model_tournaments_mutations_deleteTournament;
  "_model/tournaments/mutations/endTournament": typeof _model_tournaments_mutations_endTournament;
  "_model/tournaments/mutations/openTournamentRound": typeof _model_tournaments_mutations_openTournamentRound;
  "_model/tournaments/mutations/publishTournament": typeof _model_tournaments_mutations_publishTournament;
  "_model/tournaments/mutations/startTournament": typeof _model_tournaments_mutations_startTournament;
  "_model/tournaments/mutations/updateTournament": typeof _model_tournaments_mutations_updateTournament;
  "_model/tournaments/queries/getTournament": typeof _model_tournaments_queries_getTournament;
  "_model/tournaments/queries/getTournamentOpenRound": typeof _model_tournaments_queries_getTournamentOpenRound;
  "_model/tournaments/queries/getTournamentRankings": typeof _model_tournaments_queries_getTournamentRankings;
  "_model/tournaments/queries/getTournaments": typeof _model_tournaments_queries_getTournaments;
  "_model/tournaments/queries/getTournamentsByStatus": typeof _model_tournaments_queries_getTournamentsByStatus;
  "_model/utils/_helpers/mockData": typeof _model_utils__helpers_mockData;
  "_model/utils/_helpers/testUsers": typeof _model_utils__helpers_testUsers;
  "_model/utils/createTestTournament": typeof _model_utils_createTestTournament;
  "_model/utils/createTestTournamentMatchResults": typeof _model_utils_createTestTournamentMatchResults;
  "_model/utils/deleteTestTournament": typeof _model_utils_deleteTestTournament;
  "_model/utils/index": typeof _model_utils_index;
  "auth/ResendOtpPasswordReset": typeof auth_ResendOtpPasswordReset;
  "auth/ResendOtpVerification": typeof auth_ResendOtpVerification;
  auth: typeof auth;
  "common/errors": typeof common_errors;
  "common/fowV4/fowV4GameSystemConfig": typeof common_fowV4_fowV4GameSystemConfig;
  "common/fowV4/fowV4MatchOutcomeType": typeof common_fowV4_fowV4MatchOutcomeType;
  "common/fowV4/fowV4MatchResultDetails": typeof common_fowV4_fowV4MatchResultDetails;
  "common/fowV4/getMission": typeof common_fowV4_getMission;
  "common/fowV4/getMissionPack": typeof common_fowV4_getMissionPack;
  "common/location": typeof common_location;
  "common/tournamentStatus": typeof common_tournamentStatus;
  "common/userDataVisibilityLevel": typeof common_userDataVisibilityLevel;
  "friendships/confirmFriendship": typeof friendships_confirmFriendship;
  "friendships/createFriendship": typeof friendships_createFriendship;
  "friendships/deleteFriendship": typeof friendships_deleteFriendship;
  "friendships/fetchFriendship": typeof friendships_fetchFriendship;
  "friendships/fetchFriendshipRequests": typeof friendships_fetchFriendshipRequests;
  "friendships/fetchFriendshipUserIdsByUserId": typeof friendships_fetchFriendshipUserIdsByUserId;
  "friendships/index": typeof friendships_index;
  generateFileUploadUrl: typeof generateFileUploadUrl;
  http: typeof http;
  "matchResultComments/index": typeof matchResultComments_index;
  "matchResultComments/mutations": typeof matchResultComments_mutations;
  "matchResultComments/queries": typeof matchResultComments_queries;
  "matchResultLikes/index": typeof matchResultLikes_index;
  "matchResultLikes/mutations": typeof matchResultLikes_mutations;
  "matchResultLikes/queries": typeof matchResultLikes_queries;
  "matchResults/fetchMatchResult": typeof matchResults_fetchMatchResult;
  "matchResults/fetchMatchResultList": typeof matchResults_fetchMatchResultList;
  "matchResults/index": typeof matchResults_index;
  "matchResults/mutations": typeof matchResults_mutations;
  "photos/index": typeof photos_index;
  "photos/mutations": typeof photos_mutations;
  "photos/queries": typeof photos_queries;
  "static/currencyCodes": typeof static_currencyCodes;
  "static/fowV4/dynamicPointsVersions": typeof static_fowV4_dynamicPointsVersions;
  "static/fowV4/eras": typeof static_fowV4_eras;
  "static/fowV4/factions": typeof static_fowV4_factions;
  "static/fowV4/fowV4BattlePlan": typeof static_fowV4_fowV4BattlePlan;
  "static/fowV4/fowV4RankingFactors": typeof static_fowV4_fowV4RankingFactors;
  "static/fowV4/lessonsFromTheFrontVersions": typeof static_fowV4_lessonsFromTheFrontVersions;
  "static/fowV4/missionPacks": typeof static_fowV4_missionPacks;
  "static/gameSystems": typeof static_gameSystems;
  "static/tournamentPairingMethods": typeof static_tournamentPairingMethods;
  "static/tournamentPhases": typeof static_tournamentPhases;
  tournamentCompetitors: typeof tournamentCompetitors;
  tournamentPairings: typeof tournamentPairings;
  tournamentTimers: typeof tournamentTimers;
  tournaments: typeof tournaments;
  "users/checkUsernameExists": typeof users_checkUsernameExists;
  "users/fetchCurrentUser": typeof users_fetchCurrentUser;
  "users/fetchUser": typeof users_fetchUser;
  "users/fetchUserList": typeof users_fetchUserList;
  "users/index": typeof users_index;
  "users/updateAvatar": typeof users_updateAvatar;
  "users/updateUser": typeof users_updateUser;
  "users/utils/checkUserTournamentRelationship": typeof users_utils_checkUserTournamentRelationship;
  "users/utils/getAvatarUrl": typeof users_utils_getAvatarUrl;
  "users/utils/getLimitedUser": typeof users_utils_getLimitedUser;
  "users/utils/redactUserInfo": typeof users_utils_redactUserInfo;
  utils: typeof utils;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
